"""add is_daily and last_updated to game scores

Revision ID: 756185cbcbd5
Revises: 
Create Date: 2026-09-09 09:49:22.902024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '756185cbcbd5'
down_revision: Union[str, Sequence[str], None] = '70318725edaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default required so existing rows get a value for this new NOT NULL column.
    op.add_column(
        'h2h_games', sa.Column('is_daily', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column('h2h_games', sa.Column('last_updated', sa.DateTime(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('h2h_games', 'last_updated')
    op.drop_column('h2h_games', 'is_daily')
    # ### end Alembic commands ###
