"""add allowed_accounts table

Revision ID: 89713fe9c84e
Revises: 756185cbcbd5
Create Date: 2026-09-09 10:20:44.304603

"""
import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89713fe9c84e'
down_revision: Union[str, Sequence[str], None] = '756185cbcbd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    allowed_accounts = op.create_table('allowed_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', name='accountstatus', native_enum=False, length=16), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allowed_accounts_email'), 'allowed_accounts', ['email'], unique=True)
    # ### end Alembic commands ###

    # Seed the first approved admin account so the allowlist isn't empty on a fresh deploy.
    op.bulk_insert(
        allowed_accounts,
        [
            {
                "email": "lauriesmith20@hotmail.co.uk",
                "display_name": "Laurie Smith",
                "status": "APPROVED",
                "is_admin": True,
                "created_at": datetime.datetime.now(datetime.UTC),
            }
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_allowed_accounts_email'), table_name='allowed_accounts')
    op.drop_table('allowed_accounts')
    # ### end Alembic commands ###
