"""add friends and beer bets, profile fields

Revision ID: b8278ac8b184
Revises: 65ba62b7e0c5
Create Date: 2026-09-11 14:55:47.643878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8278ac8b184'
down_revision: Union[str, Sequence[str], None] = '65ba62b7e0c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beer_bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('stake', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AWAITING_CONFIRMATION', 'OPEN', 'RESOLVED', name='beerbetstatus', native_enum=False, length=24), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['allowed_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opponent_id'], ['allowed_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['allowed_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('addressee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', name='friendshipstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['addressee_id'], ['allowed_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['allowed_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id')
    )
    op.add_column('allowed_accounts', sa.Column('nickname', sa.String(), nullable=True))
    op.add_column(
        'allowed_accounts',
        sa.Column('avatar_color', sa.String(), nullable=False, server_default='#66B2FF'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('allowed_accounts', 'avatar_color')
    op.drop_column('allowed_accounts', 'nickname')
    op.drop_table('friendships')
    op.drop_table('beer_bets')
    # ### end Alembic commands ###
