"""add cancelled status fields and settlement flag to beer bets

Revision ID: c47a0d16585c
Revises: 1da2aae1cc85
Create Date: 2026-09-11 15:18:35.522423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47a0d16585c'
down_revision: Union[str, Sequence[str], None] = '1da2aae1cc85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'beer_bets',
        sa.Column('is_settlement', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('beer_bets', sa.Column('cancelled_at', sa.DateTime(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('beer_bets', 'cancelled_at')
    op.drop_column('beer_bets', 'is_settlement')
    # ### end Alembic commands ###
