"""add account_tile_access table

Revision ID: c6902403806d
Revises: 89713fe9c84e
Create Date: 2026-09-09 12:25:36.435288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6902403806d'
down_revision: Union[str, Sequence[str], None] = '89713fe9c84e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_tile_access',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('tile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['allowed_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tile_id'], ['tiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'tile_id')
    )
    # ### end Alembic commands ###

    # Backfill: grant existing approved, non-admin accounts access to all current tiles so
    # this new allowlist doesn't silently hide tiles they could already see.
    op.execute(
        """
        INSERT INTO account_tile_access (account_id, tile_id)
        SELECT allowed_accounts.id, tiles.id
        FROM allowed_accounts, tiles
        WHERE allowed_accounts.status = 'APPROVED' AND allowed_accounts.is_admin = 0
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_tile_access')
    # ### end Alembic commands ###
