"""add plant quiz tables

Revision ID: ec6f01ac6169
Revises: c6902403806d
Create Date: 2026-09-09 12:56:36.556013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec6f01ac6169'
down_revision: Union[str, Sequence[str], None] = 'c6902403806d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_quiz_big_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plant_quiz_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Add a homepage tile for the new feature (skip if a tile with this href already exists).
    op.execute(
        """
        INSERT INTO tiles (title, href, color, icon)
        SELECT 'Plant Quiz', '/plant-quiz', '#B9E0A5', 'sprout'
        WHERE NOT EXISTS (SELECT 1 FROM tiles WHERE href = '/plant-quiz')
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM tiles WHERE href = '/plant-quiz'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant_quiz_scores')
    op.drop_table('plant_quiz_big_scores')
    # ### end Alembic commands ###
