import fineUrl from '../data/worldFine.json?url'
import shapesUrl from '../data/worldShapes.json?url'
import graph from '../data/worldGraph.json'

export const MAP_WIDTH = 960
export const MAP_HEIGHT = 500

export interface Country {
  id: number
  name: string
  /** Simplified outline, used at world/continent zoom (about 3x fewer points). */
  d: string
  center: [number, number]
}

/** Which countries border which. Small and bundled, so the game can start without waiting for the map. */
export interface WorldGraph {
  names: string[]
  /** `adjacency[i]` lists the indexes of countries sharing a land border with country `i`. */
  adjacency: number[][]
}

export interface World {
  countries: Country[]
  adjacency: number[][]
}

// Generated by scripts/generate-world.ts (npm run gen:world).
export const WORLD_GRAPH: WorldGraph = graph

let worldPromise: Promise<World> | null = null

// The outlines are a lot of path data, so they are fetched on demand and cached for the session.
export function loadWorld(): Promise<World> {
  worldPromise ??= fetchWorld().catch((error) => {
    worldPromise = null
    throw error
  })
  return worldPromise
}

async function fetchWorld(): Promise<World> {
  const response = await fetch(shapesUrl)
  if (!response.ok) throw new Error('Failed to load map data')
  const shapes = (await response.json()) as { d: string[]; center: [number, number][] }
  const countries = WORLD_GRAPH.names.map((name, id) => ({
    id,
    name,
    d: shapes.d[id],
    center: shapes.center[id],
  }))
  return { countries, adjacency: WORLD_GRAPH.adjacency }
}

let finePromise: Promise<string[]> | null = null

/** Full-detail outlines by country id, for when the map is zoomed right in (about 3x the size of the coarse ones). */
export function loadFineOutlines(): Promise<string[]> {
  finePromise ??= fetch(fineUrl)
    .then((response) => {
      if (!response.ok) throw new Error('Failed to load map detail')
      return response.json() as Promise<{ dFine: string[] }>
    })
    .then((fine) => fine.dFine)
    .catch((error) => {
      finePromise = null
      throw error
    })
  return finePromise
}

export interface RouteResult {
  /** Up to `limit` routes, each a list of country indexes from `from` to `to`. */
  routes: number[][]
  /** Total number of distinct shortest routes (may exceed `routes.length`). */
  totalRoutes: number
  /** Number of borders crossed on a shortest route. */
  borders: number
  /** Every country that sits on at least one shortest route (including both ends). */
  onAnyRoute: Set<number>
}

function bfs(adjacency: number[][], source: number): number[] {
  const dist = new Array<number>(adjacency.length).fill(-1)
  dist[source] = 0
  const queue = [source]
  for (let head = 0; head < queue.length; head++) {
    const current = queue[head]
    for (const next of adjacency[current]) {
      if (dist[next] === -1) {
        dist[next] = dist[current] + 1
        queue.push(next)
      }
    }
  }
  return dist
}

/** All fewest-border routes between two countries, or null if there is no land route. */
export function shortestRoutes(adjacency: number[][], from: number, to: number, limit = 12): RouteResult | null {
  if (from === to) return null
  const fromDist = bfs(adjacency, from)
  const toDist = bfs(adjacency, to)
  const borders = fromDist[to]
  if (borders === -1) return null

  const onAnyRoute = new Set<number>()
  fromDist.forEach((d, i) => {
    if (d !== -1 && toDist[i] !== -1 && d + toDist[i] === borders) onAnyRoute.add(i)
  })

  // Count routes with DP over BFS layers, then enumerate up to `limit` of them.
  const count = new Map<number, number>()
  const countFrom = (node: number): number => {
    if (node === to) return 1
    const cached = count.get(node)
    if (cached !== undefined) return cached
    let total = 0
    for (const next of adjacency[node]) {
      if (onAnyRoute.has(next) && fromDist[next] === fromDist[node] + 1) total += countFrom(next)
    }
    count.set(node, total)
    return total
  }
  const totalRoutes = countFrom(from)

  const routes: number[][] = []
  const walk = (node: number, trail: number[]) => {
    if (routes.length >= limit) return
    const next = [...trail, node]
    if (node === to) {
      routes.push(next)
      return
    }
    for (const n of adjacency[node]) {
      if (onAnyRoute.has(n) && fromDist[n] === fromDist[node] + 1) walk(n, next)
    }
  }
  walk(from, [])

  return { routes, totalRoutes, borders, onAnyRoute }
}
