// Generated once from the ISO 3166 numeric ids in world-atlas (Natural Earth) — no runtime dependency.
// Keyed by the Natural Earth country name used by countryGraph. Somaliland, Northern Cyprus and two
// disputed/uninhabited shapes have no ISO code or flag, so they aren't playable and are left out.

export interface CountryMeta {
  /** ISO 3166-1 alpha-2, lower case: used for the flag image. */
  code: string
  /** Friendlier display name where Natural Earth abbreviates (e.g. "Dem. Rep. Congo"). */
  label?: string
  /** Other names people type for it. */
  aliases?: string[]
}

export const COUNTRY_META: Record<string, CountryMeta> = {
  'Afghanistan': { code: 'af' },
  'Åland': { code: 'ax' },
  'Albania': { code: 'al' },
  'Algeria': { code: 'dz' },
  'American Samoa': { code: 'as' },
  'Andorra': { code: 'ad' },
  'Angola': { code: 'ao' },
  'Anguilla': { code: 'ai' },
  'Antigua and Barb.': { code: 'ag', label: 'Antigua and Barbuda' },
  'Argentina': { code: 'ar' },
  'Armenia': { code: 'am' },
  'Aruba': { code: 'aw' },
  'Ashmore and Cartier Is.': { code: 'au', label: 'Ashmore and Cartier Islands' },
  'Australia': { code: 'au' },
  'Austria': { code: 'at' },
  'Azerbaijan': { code: 'az' },
  'Bahamas': { code: 'bs', aliases: ['the bahamas'] },
  'Bahrain': { code: 'bh' },
  'Bangladesh': { code: 'bd' },
  'Barbados': { code: 'bb' },
  'Belarus': { code: 'by' },
  'Belgium': { code: 'be' },
  'Belize': { code: 'bz' },
  'Benin': { code: 'bj' },
  'Bermuda': { code: 'bm' },
  'Bhutan': { code: 'bt' },
  'Bolivia': { code: 'bo' },
  'Bosnia and Herz.': { code: 'ba', label: 'Bosnia and Herzegovina', aliases: ['bosnia'] },
  'Botswana': { code: 'bw' },
  'Br. Indian Ocean Ter.': { code: 'io', label: 'British Indian Ocean Territory' },
  'Brazil': { code: 'br' },
  'British Virgin Is.': { code: 'vg', label: 'British Virgin Islands' },
  'Brunei': { code: 'bn', aliases: ['brunei darussalam'] },
  'Bulgaria': { code: 'bg' },
  'Burkina Faso': { code: 'bf' },
  'Burundi': { code: 'bi' },
  'Cabo Verde': { code: 'cv', aliases: ['cape verde'] },
  'Cambodia': { code: 'kh' },
  'Cameroon': { code: 'cm' },
  'Canada': { code: 'ca' },
  'Cayman Is.': { code: 'ky', label: 'Cayman Islands' },
  'Central African Rep.': { code: 'cf', label: 'Central African Republic' },
  'Chad': { code: 'td' },
  'Chile': { code: 'cl' },
  'China': { code: 'cn' },
  'Colombia': { code: 'co' },
  'Comoros': { code: 'km' },
  'Congo': { code: 'cg', label: 'Republic of the Congo', aliases: ['congo brazzaville', 'congo'] },
  'Cook Is.': { code: 'ck', label: 'Cook Islands' },
  'Costa Rica': { code: 'cr' },
  'Côte d\'Ivoire': { code: 'ci', aliases: ['ivory coast'] },
  'Croatia': { code: 'hr' },
  'Cuba': { code: 'cu' },
  'Curaçao': { code: 'cw' },
  'Cyprus': { code: 'cy' },
  'Czechia': { code: 'cz', aliases: ['czech republic'] },
  'Dem. Rep. Congo': { code: 'cd', label: 'DR Congo', aliases: ['democratic republic of the congo', 'drc', 'congo kinshasa', 'dem rep congo'] },
  'Denmark': { code: 'dk' },
  'Djibouti': { code: 'dj' },
  'Dominica': { code: 'dm' },
  'Dominican Rep.': { code: 'do', label: 'Dominican Republic' },
  'Ecuador': { code: 'ec' },
  'Egypt': { code: 'eg' },
  'El Salvador': { code: 'sv' },
  'Eq. Guinea': { code: 'gq', label: 'Equatorial Guinea' },
  'Eritrea': { code: 'er' },
  'Estonia': { code: 'ee' },
  'eSwatini': { code: 'sz', label: 'Eswatini', aliases: ['swaziland'] },
  'Ethiopia': { code: 'et' },
  'Faeroe Is.': { code: 'fo', label: 'Faroe Islands' },
  'Falkland Is.': { code: 'fk', label: 'Falkland Islands' },
  'Fiji': { code: 'fj' },
  'Finland': { code: 'fi' },
  'Fr. Polynesia': { code: 'pf', label: 'French Polynesia' },
  'Fr. S. Antarctic Lands': { code: 'tf', label: 'French Southern Lands' },
  'France': { code: 'fr' },
  'Gabon': { code: 'ga' },
  'Gambia': { code: 'gm', aliases: ['the gambia'] },
  'Georgia': { code: 'ge' },
  'Germany': { code: 'de' },
  'Ghana': { code: 'gh' },
  'Greece': { code: 'gr' },
  'Greenland': { code: 'gl' },
  'Grenada': { code: 'gd' },
  'Guam': { code: 'gu' },
  'Guatemala': { code: 'gt' },
  'Guernsey': { code: 'gg' },
  'Guinea': { code: 'gn' },
  'Guinea-Bissau': { code: 'gw' },
  'Guyana': { code: 'gy' },
  'Haiti': { code: 'ht' },
  'Heard I. and McDonald Is.': { code: 'hm', label: 'Heard and McDonald Islands' },
  'Honduras': { code: 'hn' },
  'Hong Kong': { code: 'hk' },
  'Hungary': { code: 'hu' },
  'Iceland': { code: 'is' },
  'India': { code: 'in' },
  'Indonesia': { code: 'id' },
  'Iran': { code: 'ir', aliases: ['islamic republic of iran'] },
  'Iraq': { code: 'iq' },
  'Ireland': { code: 'ie' },
  'Isle of Man': { code: 'im' },
  'Israel': { code: 'il' },
  'Italy': { code: 'it' },
  'Jamaica': { code: 'jm' },
  'Japan': { code: 'jp' },
  'Jersey': { code: 'je' },
  'Jordan': { code: 'jo' },
  'Kazakhstan': { code: 'kz' },
  'Kenya': { code: 'ke' },
  'Kiribati': { code: 'ki' },
  'Kosovo': { code: 'xk' },
  'Kuwait': { code: 'kw' },
  'Kyrgyzstan': { code: 'kg' },
  'Laos': { code: 'la', aliases: ['lao'] },
  'Latvia': { code: 'lv' },
  'Lebanon': { code: 'lb' },
  'Lesotho': { code: 'ls' },
  'Liberia': { code: 'lr' },
  'Libya': { code: 'ly' },
  'Liechtenstein': { code: 'li' },
  'Lithuania': { code: 'lt' },
  'Luxembourg': { code: 'lu' },
  'Macao': { code: 'mo' },
  'Macedonia': { code: 'mk', label: 'North Macedonia', aliases: ['macedonia'] },
  'Madagascar': { code: 'mg' },
  'Malawi': { code: 'mw' },
  'Malaysia': { code: 'my' },
  'Maldives': { code: 'mv' },
  'Mali': { code: 'ml' },
  'Malta': { code: 'mt' },
  'Marshall Is.': { code: 'mh', label: 'Marshall Islands' },
  'Mauritania': { code: 'mr' },
  'Mauritius': { code: 'mu' },
  'Mexico': { code: 'mx' },
  'Micronesia': { code: 'fm' },
  'Moldova': { code: 'md' },
  'Monaco': { code: 'mc' },
  'Mongolia': { code: 'mn' },
  'Montenegro': { code: 'me' },
  'Montserrat': { code: 'ms' },
  'Morocco': { code: 'ma' },
  'Mozambique': { code: 'mz' },
  'Myanmar': { code: 'mm', aliases: ['burma'] },
  'N. Mariana Is.': { code: 'mp', label: 'Northern Mariana Islands' },
  'Namibia': { code: 'na' },
  'Nauru': { code: 'nr' },
  'Nepal': { code: 'np' },
  'Netherlands': { code: 'nl', aliases: ['holland'] },
  'New Caledonia': { code: 'nc' },
  'New Zealand': { code: 'nz' },
  'Nicaragua': { code: 'ni' },
  'Niger': { code: 'ne' },
  'Nigeria': { code: 'ng' },
  'Niue': { code: 'nu' },
  'Norfolk Island': { code: 'nf' },
  'North Korea': { code: 'kp', aliases: ['dprk'] },
  'Norway': { code: 'no' },
  'Oman': { code: 'om' },
  'Pakistan': { code: 'pk' },
  'Palau': { code: 'pw' },
  'Palestine': { code: 'ps', aliases: ['state of palestine'] },
  'Panama': { code: 'pa' },
  'Papua New Guinea': { code: 'pg' },
  'Paraguay': { code: 'py' },
  'Peru': { code: 'pe' },
  'Philippines': { code: 'ph' },
  'Pitcairn Is.': { code: 'pn', label: 'Pitcairn Islands' },
  'Poland': { code: 'pl' },
  'Portugal': { code: 'pt' },
  'Puerto Rico': { code: 'pr' },
  'Qatar': { code: 'qa' },
  'Romania': { code: 'ro' },
  'Russia': { code: 'ru', aliases: ['russian federation'] },
  'Rwanda': { code: 'rw' },
  'S. Geo. and the Is.': { code: 'gs', label: 'South Georgia' },
  'S. Sudan': { code: 'ss', label: 'South Sudan' },
  'Saint Helena': { code: 'sh' },
  'Saint Lucia': { code: 'lc' },
  'Samoa': { code: 'ws' },
  'San Marino': { code: 'sm' },
  'São Tomé and Principe': { code: 'st' },
  'Saudi Arabia': { code: 'sa' },
  'Senegal': { code: 'sn' },
  'Serbia': { code: 'rs' },
  'Seychelles': { code: 'sc' },
  'Sierra Leone': { code: 'sl' },
  'Singapore': { code: 'sg' },
  'Sint Maarten': { code: 'sx' },
  'Slovakia': { code: 'sk' },
  'Slovenia': { code: 'si' },
  'Solomon Is.': { code: 'sb', label: 'Solomon Islands' },
  'Somalia': { code: 'so' },
  'South Africa': { code: 'za' },
  'South Korea': { code: 'kr', aliases: ['korea', 'republic of korea'] },
  'Spain': { code: 'es' },
  'Sri Lanka': { code: 'lk' },
  'St-Barthélemy': { code: 'bl', label: 'Saint Barthélemy' },
  'St-Martin': { code: 'mf', label: 'Saint Martin' },
  'St. Kitts and Nevis': { code: 'kn', label: 'Saint Kitts and Nevis' },
  'St. Pierre and Miquelon': { code: 'pm', label: 'Saint Pierre and Miquelon' },
  'St. Vin. and Gren.': { code: 'vc', label: 'Saint Vincent and the Grenadines' },
  'Sudan': { code: 'sd' },
  'Suriname': { code: 'sr' },
  'Sweden': { code: 'se' },
  'Switzerland': { code: 'ch' },
  'Syria': { code: 'sy', aliases: ['syrian arab republic'] },
  'Taiwan': { code: 'tw' },
  'Tajikistan': { code: 'tj' },
  'Tanzania': { code: 'tz' },
  'Thailand': { code: 'th' },
  'Timor-Leste': { code: 'tl', aliases: ['east timor'] },
  'Togo': { code: 'tg' },
  'Tonga': { code: 'to' },
  'Trinidad and Tobago': { code: 'tt' },
  'Tunisia': { code: 'tn' },
  'Turkey': { code: 'tr', aliases: ['turkiye'] },
  'Turkmenistan': { code: 'tm' },
  'Turks and Caicos Is.': { code: 'tc', label: 'Turks and Caicos Islands' },
  'U.S. Virgin Is.': { code: 'vi', label: 'US Virgin Islands' },
  'Uganda': { code: 'ug' },
  'Ukraine': { code: 'ua' },
  'United Arab Emirates': { code: 'ae', aliases: ['uae'] },
  'United Kingdom': { code: 'gb', aliases: ['uk', 'britain', 'great britain', 'england', 'scotland', 'wales'] },
  'United States of America': { code: 'us', label: 'United States', aliases: ['usa', 'us', 'america', 'united states of america'] },
  'Uruguay': { code: 'uy' },
  'Uzbekistan': { code: 'uz' },
  'Vanuatu': { code: 'vu' },
  'Vatican': { code: 'va', label: 'Vatican City', aliases: ['holy see', 'vatican'] },
  'Venezuela': { code: 've' },
  'Vietnam': { code: 'vn' },
  'W. Sahara': { code: 'eh', label: 'Western Sahara' },
  'Wallis and Futuna Is.': { code: 'wf', label: 'Wallis and Futuna' },
  'Yemen': { code: 'ye' },
  'Zambia': { code: 'zm' },
  'Zimbabwe': { code: 'zw' },
}
